name: Version Check
run-name: Version Check for "${{ github.event.pull_request.title }}"
on: pull_request_target

jobs:
  call-reusable-workflow:
    uses: makotocchi/github-actions-test/.github/workflows/version_check_workflow.yml@main
    permissions:
      contents: read
      pull-requests: write
